In [11]:
import numpy as np

a = np.random.randn(5)

In [12]:
print(a)

[-1.66595408  0.61742935  1.09357343 -2.22995537 -0.32241553]


In [13]:
print(a.shape)  # "rank 1 array"

(5,)


In [14]:
print(a.T)

[-1.66595408  0.61742935  1.09357343 -2.22995537 -0.32241553]


In [15]:
print(np.dot(a,a.T))

9.42917758138


In [16]:
a = np.random.randn(5,1)
print(a)

[[ 0.12564038]
 [-1.17645512]
 [-1.01050836]
 [ 0.23765113]
 [-0.80985031]]


In [17]:
print(a.T)

[[ 0.12564038 -1.17645512 -1.01050836  0.23765113 -0.80985031]]


In [18]:
print(np.dot(a,a.T))

[[ 0.01578551 -0.14781027 -0.12696066  0.02985858 -0.1017499 ]
 [-0.14781027  1.38404665  1.18881774 -0.27958589  0.95275254]
 [-0.12696066  1.18881774  1.02112715 -0.24014846  0.81836051]
 [ 0.02985858 -0.27958589 -0.24014846  0.05647806 -0.19246184]
 [-0.1017499   0.95275254  0.81836051 -0.19246184  0.65585753]]


In [19]:
print(a.shape)

(5, 1)


In [22]:
assert(a.shape == (5, 1))